ORG       = rand
CONTAINER = page
TAG       = latest
git_user  = $(ID)
git_email = $(ID)@$(ORG)
passphrase = "$(shell pass show rand/$(ID)/master)"
RESTIC_REPOSITORY ?= /Volumes/restic
RESTIC_PASSWORD_COMMAND = "pass show $(ORG)/$(ID)/backup"
WORKDIR   ?= /Volumes/workspace
KEYS      = $(WORKDIR)/$(ORG)/$(git_user)/gnupg
ADDRESS   = $(WORKDIR)/$(ORG)/$(git_user)/address
PASSWORDS = $(WORKDIR)/$(ORG)/$(git_user)/passwords
