ORG       = protonmail.com
CONTAINER = page
TAG       = latest
git_user  = $(ID)
git_email = $(ID)@$(ORG)
passphrase = "$(shell pass show $(ORG)/$(ID)"
RESTIC_REPOSITORY ?= /Volumes/restic
RESTIC_PASSWORD_COMMAND = "pass show $(ORG)/$(ID).bak"
WORKDIR   ?= /Volumes/workspace
KEYS      = $(WORKDIR)/$(ORG)/$(git_user)/gnupg
ADDRESS   = $(WORKDIR)/$(ORG)/$(git_user)/address
PASSWORDS = $(WORKDIR)/$(ORG)/$(git_user)/passwords
