ORG       = rand
CONTAINER = page
TAG       = latest
git_user  = $(ID)
git_email = $(ID)@$(ORG).org
passphrase = "$(shell pass show $(git_email))"
SECURE_ERASE_LEVEL = 0 # Note: Level 2, 3, or 4 secure erases can take an extremely long time.
WORKDIR   ?= /Volumes/workspace
RESTIC_REPOSITORY = /Volumes/restic
RESTIC_PASSWORD_COMMAND = "pass show rand.org/$(ID).bak"
KEYS      = $(WORKDIR)/$(ORG)/$(git_user)/gnupg
ADDRESS   = $(WORKDIR)/$(ORG)/$(git_user)/address
PASSWORDS = $(WORKDIR)/$(ORG)/$(git_user)/passwords
